/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthAgentsRouteImport } from './routes/_auth/agents'
import { Route as AuthChatRouteImport } from './routes/_auth/chat'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthMemoryRouteImport } from './routes/_auth/memory'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthSkillsRouteImport } from './routes/_auth/skills'
import { Route as AuthTasksRouteImport } from './routes/_auth/tasks'
import { Route as AuthChatIndexRouteImport } from './routes/_auth/chat.index'
import { Route as AuthChatThreadIdRouteImport } from './routes/_auth/chat.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAgentsRoute = AuthAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChatRoute = AuthChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMemoryRoute = AuthMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSkillsRoute = AuthSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTasksRoute = AuthTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChatIndexRoute = AuthChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthChatRoute,
} as any)
const AuthChatThreadIdRoute = AuthChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AuthChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agents': typeof AuthAgentsRoute
  '/chat': typeof AuthChatRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/memory': typeof AuthMemoryRoute
  '/settings': typeof AuthSettingsRoute
  '/skills': typeof AuthSkillsRoute
  '/tasks': typeof AuthTasksRoute
  '/chat/$threadId': typeof AuthChatThreadIdRoute
  '/chat/': typeof AuthChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agents': typeof AuthAgentsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/memory': typeof AuthMemoryRoute
  '/settings': typeof AuthSettingsRoute
  '/skills': typeof AuthSkillsRoute
  '/tasks': typeof AuthTasksRoute
  '/chat/$threadId': typeof AuthChatThreadIdRoute
  '/chat': typeof AuthChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/agents': typeof AuthAgentsRoute
  '/_auth/chat': typeof AuthChatRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/memory': typeof AuthMemoryRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/skills': typeof AuthSkillsRoute
  '/_auth/tasks': typeof AuthTasksRoute
  '/_auth/chat/$threadId': typeof AuthChatThreadIdRoute
  '/_auth/chat/': typeof AuthChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agents'
    | '/chat'
    | '/dashboard'
    | '/memory'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/chat/$threadId'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/agents'
    | '/dashboard'
    | '/memory'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/chat/$threadId'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/agents'
    | '/_auth/chat'
    | '/_auth/dashboard'
    | '/_auth/memory'
    | '/_auth/settings'
    | '/_auth/skills'
    | '/_auth/tasks'
    | '/_auth/chat/$threadId'
    | '/_auth/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/agents': {
      id: '/_auth/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthAgentsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/chat': {
      id: '/_auth/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthChatRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/memory': {
      id: '/_auth/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AuthMemoryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/skills': {
      id: '/_auth/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AuthSkillsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tasks': {
      id: '/_auth/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthTasksRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/chat/': {
      id: '/_auth/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthChatIndexRouteImport
      parentRoute: typeof AuthChatRoute
    }
    '/_auth/chat/$threadId': {
      id: '/_auth/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthChatThreadIdRouteImport
      parentRoute: typeof AuthChatRoute
    }
  }
}

interface AuthChatRouteChildren {
  AuthChatThreadIdRoute: typeof AuthChatThreadIdRoute
  AuthChatIndexRoute: typeof AuthChatIndexRoute
}

const AuthChatRouteChildren: AuthChatRouteChildren = {
  AuthChatThreadIdRoute: AuthChatThreadIdRoute,
  AuthChatIndexRoute: AuthChatIndexRoute,
}

const AuthChatRouteWithChildren = AuthChatRoute._addFileChildren(
  AuthChatRouteChildren,
)

interface AuthRouteChildren {
  AuthAgentsRoute: typeof AuthAgentsRoute
  AuthChatRoute: typeof AuthChatRouteWithChildren
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthMemoryRoute: typeof AuthMemoryRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthSkillsRoute: typeof AuthSkillsRoute
  AuthTasksRoute: typeof AuthTasksRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAgentsRoute: AuthAgentsRoute,
  AuthChatRoute: AuthChatRouteWithChildren,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthMemoryRoute: AuthMemoryRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthSkillsRoute: AuthSkillsRoute,
  AuthTasksRoute: AuthTasksRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
